spring:
  application:
    name: tlias-web-management
  #配置数据库的连接信息
  datasource:
    #配置URL为jdbc:mysql://localhost:3306/创建的数据库的名字
    url: jdbc:mysql://192.168.100.128:3306/tlias
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234

  #Mybatis的相关配置（Mybatis是用来对数据库增删改查的JDBC包装成的框架）
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #开启驼峰命名法的映射
      map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-ai-gu
    region: cn-beijing